version: '3.8'
services:
  radio-app:
    build: .
    container_name: radio-browser
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
